FROM python:3.12-slim

RUN groupadd -r trader && useradd -r -g trader trader

WORKDIR /app

COPY topgun/requirements.txt ./topgun/requirements.txt
RUN pip install --no-cache-dir -r topgun/requirements.txt

COPY topgun ./topgun
ENV SETUPTOOLS_SCM_PRETEND_VERSION=1.0.0
RUN pip install -e ./topgun

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER trader

ENV PYTHONOPTIMIZE=2
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
