"""typing_inspect package initialization"""

from .typing_inspect import (
    is_union_type,
    is_optional_type,
    is_literal_type,
    is_final_type,
    is_new_type,
    is_generic_type,
    is_callable_type,
    is_tuple_type,
    is_typevar,
    is_classvar,
    is_forward_ref,
    get_origin,
    get_args,
    get_parameters,
    get_bound,
    get_constraints,
    get_generic_type,
    get_generic_bases,
    typed_dict_keys,
    get_forward_arg,
)

__all__ = [
    'is_union_type',
    'is_optional_type',
    'is_literal_type',
    'is_final_type',
    'is_new_type',
    'is_generic_type',
    'is_callable_type',
    'is_tuple_type',
    'is_typevar',
    'is_classvar',
    'is_forward_ref',
    'get_origin',
    'get_args',
    'get_parameters',
    'get_bound',
    'get_constraints',
    'get_generic_type',
    'get_generic_bases',
    'typed_dict_keys',
    'get_forward_arg',
]
