name: CI-CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install --upgrade pip
      - run: pip install -e .
      - run: pip install flake8 mypy types-PyYAML
      - run: flake8 bots shared --count --statistics
      - run: |
          mkdir -p /tmp/mypy_check
          cp -r bots /tmp/mypy_check/
          cp -r shared /tmp/mypy_check/
          cd /tmp/mypy_check
          mypy bots shared --ignore-missing-imports --show-error-codes

  build-push:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bot: [sherrinford, watson, gmo_board_watcher]
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: docker build -f docker/base.Dockerfile -t root-bot-base:latest .
      - run: |
          docker build -f bots/${{ matrix.bot }}/Dockerfile \
            -t ghcr.io/${{ github.repository }}/${{ matrix.bot }}:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/${{ matrix.bot }}:${{ github.sha }}
  deploy:
    if: false
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /srv/root-bot
            git pull
            docker-compose pull
            docker-compose up -d
