name: CI-CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install --upgrade pip
      - run: pip install -e .
      - run: pip install flake8 mypy types-PyYAML
      - run: flake8 topgun shared --count --statistics --exit-zero
      - run: |
          mkdir -p /tmp/mypy_check
          cp -r topgun /tmp/mypy_check/
          cp -r shared /tmp/mypy_check/
          cd /tmp/mypy_check
          mypy topgun shared --ignore-missing-imports --show-error-codes

  build-push:
    if: false  # Disabled - no bots to build in topgun library
    needs: lint
    runs-on: ubuntu-latest
  deploy:
    if: false
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /srv/root-bot
            git pull
            docker-compose pull
            docker-compose up -d
